# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'pry'

gem 'pry-byebug'
gem "tty-prompt"
gem 'pry-nav'
gem 'respec'
gem 'asciiart', '~> 0.0.9'
gem 'rmagick', '~> 2.13.4'
gem 'rainbow', '~> 2.0'


