# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'pry'

gem 'pry-byebug'
gem "tty-prompt"
gem 'pry-nav'
gem 'respec'
gem 'artii', '2.1'
gem 'colorize', '~> 0.8.1'
gem "tty-progressbar"
gem 'ocra', '~> 1.3', '>= 1.3.11'
